-- =====================================================
-- Vision: Bahasa Malaysia translation columns
-- =====================================================
-- Translations are generated by Claude (Haiku 4.5) and cached here.
-- Pages fall back to the English column when the _ms value is null.
-- =====================================================

alter table public.ministries
  add column if not exists name_ms text,
  add column if not exists description_ms text;

alter table public.initiatives
  add column if not exists problem_ms text,
  add column if not exists idea_ms text;
